<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>be.bapha.openhab.addons.bundles</groupId>
    <artifactId>be.bapha.openhab.binding.voltronic-parent</artifactId>
    <version>${this.version}</version>
  </parent>
  <groupId>be.bapha.openhab.addons.bundles</groupId>
  <artifactId>be.bapha.openhab.binding.voltronic</artifactId>
  <version>${this.version}</version>
  <packaging>kar</packaging>

  <dependencies>
    <dependency>
      <groupId>org.apache.karaf.features</groupId>
      <artifactId>framework</artifactId>
      <version>${karaf.version}</version>
      <type>kar</type>
      <scope>provided</scope>
      <optional>true</optional>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.apache.karaf.features</groupId>
      <artifactId>standard</artifactId>
      <version>${karaf.version}</version>
      <classifier>features</classifier>
      <type>xml</type>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>be.bapha.openhab.addons.bundles</groupId>
      <artifactId>be.bapha.openhab.binding.voltronic-bundle</artifactId>
      <version>${this.version}</version>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-resources-plugin</artifactId>
        <version>3.4.0</version>
      </plugin>
      <plugin>
        <groupId>org.apache.karaf.tooling</groupId>
        <artifactId>karaf-maven-plugin</artifactId>
        <version>${karaf.version}</version>
        <extensions>true</extensions>
        <configuration>
          <archive>
            <addMavenDescriptor>false</addMavenDescriptor>
            <manifest>
              <addDefaultEntries>false</addDefaultEntries>
            </manifest>
          </archive>
          <!-- <startLevel>80</startLevel> -->
          <aggregateFeatures>true</aggregateFeatures>
          <failOnDependencyChange>false</failOnDependencyChange>
          <logDependencyChanges>true</logDependencyChanges>
          <overwriteChangedDependencies>true</overwriteChangedDependencies>
        </configuration>
        <executions>
          <execution>
            <id>compile</id>
            <goals>
              <goal>features-generate-descriptor</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <inputFile>${feature.directory}</inputFile>
            </configuration>
          </execution>
          <execution>
            <id>karaf-feature-verification</id>
            <goals>
              <goal>verify</goal>
            </goals>
            <phase>verify</phase>
            <configuration>
              <descriptors combine.children="append">
                <!-- Apache Karaf -->
                <descriptor>mvn:org.apache.karaf.features/framework/${karaf.version}/xml/features</descriptor>
                <descriptor>mvn:org.apache.karaf.features/standard/${karaf.version}/xml/features</descriptor>
                <!-- Current feature under verification -->
                <descriptor>file:${project.build.directory}/feature/feature.xml</descriptor>
              </descriptors>
              <distribution>org.apache.karaf.features:framework</distribution>
              <javase>${oh.java.version}</javase>
              <framework>
                <feature>framework</feature>
              </framework>
              <features>
                <feature>xxx-openhab-*</feature>
              </features>
              <verifyTransitive>false</verifyTransitive>
              <ignoreMissingConditions>true</ignoreMissingConditions>
              <fail>first</fail>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
