<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <groupId>be.bapha.openhab.addons.bundles</groupId>
  <artifactId>be.bapha.openhab.binding.voltronic-parent</artifactId>
  <version>${this.version}</version>
  <packaging>pom</packaging>

  <name>openHAB Add-ons :: Bundles :: Voltronic Inverter Binding</name>
  <modules>
    <module>jar</module>
    <module>kar</module>
  </modules>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <this.version>5.0.20260929</this.version>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
    <ohc.version>5.0.0</ohc.version>
    <sat.version>0.18.0</sat.version>
    <spotless.eclipse.wtp.version>4.21.0</spotless.eclipse.wtp.version>
    <spotless.eclipse.version>4.25</spotless.eclipse.version>
    <karaf.version>4.4.12</karaf.version>
  </properties>
  <repositories>
    <repository>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <id>openhab-release</id>
      <url>https://openhab.jfrog.io/artifactory/libs-release</url>
    </repository>
    <repository>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <id>openhab-snapshot</id>
      <url>https://openhab.jfrog.io/artifactory/libs-snapshot</url>
    </repository>
  </repositories>
  <build>
    <plugins>
      <plugin>
        <groupId>org.openhab.core.tools</groupId>
        <artifactId>i18n-maven-plugin</artifactId>
        <version>${ohc.version}</version>
      </plugin>
      <plugin>
        <groupId>com.diffplug.spotless</groupId>
        <artifactId>spotless-maven-plugin</artifactId>
        <version>2.44.3</version>
        <configuration>
          <java>
            <eclipse>
              <file>openhab_codestyle.xml</file>
              <version>${spotless.eclipse.version}</version>
            </eclipse>
            <removeUnusedImports/>
            <importOrder>
              <file>openhab.importorder</file>
            </importOrder>
            <endWithNewline/>
          </java>
          <pom>
            <sortPom>
              <expandEmptyElements>false</expandEmptyElements>
              <indentAttribute>schemaLocation</indentAttribute>
              <predefinedSortOrder>recommended_2008_06</predefinedSortOrder>
              <sortDependencyExclusions/>
              <sortDependencyManagement/>
            </sortPom>
          </pom>
          <formats>
            <format>
              <!-- *.xml -->
              <includes>
                <include>src/**/*.xml</include>
                <include>schema/**/*.xsd</include>
              </includes>
              <excludes>
                <exclude>**/feature.xml</exclude>
                <exclude>**/pom.xml</exclude>
              </excludes>
              <eclipseWtp>
                <type>XML</type>
                <files>
                  <file>openhab_wst_xml_files.prefs</file>
                </files>
                <version>${spotless.eclipse.wtp.version}</version>
              </eclipseWtp>
              <trimTrailingWhitespace/>
              <endWithNewline/>
            </format>
            <format>
              <!-- feature.xml -->
              <includes>
                <include>**/src/main/feature/feature.xml</include>
              </includes>
              <eclipseWtp>
                <type>XML</type>
                <files>
                  <file>openhab_wst_feature_file.prefs</file>
                </files>
                <version>${spotless.eclipse.wtp.version}</version>
              </eclipseWtp>
              <trimTrailingWhitespace/>
              <endWithNewline/>
            </format>
          </formats>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.openhab.tools</groupId>
            <artifactId>openhab-codestyle</artifactId>
            <version>${sat.version}</version>
          </dependency>
        </dependencies>
        <executions>
          <execution>
            <id>codestyle_check</id>
            <goals>
              <goal>check</goal>
            </goals>
            <phase>initialize</phase>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-install-plugin</artifactId>
        <version>3.1.4</version>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-deploy-plugin</artifactId>
        <version>3.1.4</version>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.15.0</version>
        <configuration>
          <compilerId>eclipse</compilerId>
          <compilerArgs>
            <arg>-annotationpath</arg>
            <arg>CLASSPATH</arg>
            <arg>-classpath</arg>
            <arg>${project.build.directory}/dependency</arg>
            <arg>-err:+nullAnnot(org.eclipse.jdt.annotation.Nullable|org.eclipse.jdt.annotation.NonNull|org.eclipse.jdt.annotation.NonNullByDefault),+inheritNullAnnot,+nullAnnotConflict,-nullUncheckedConversion</arg>
            <arg>-warn:+null,+inheritNullAnnot,-nullUncheckedConversion,+nullAnnotRedundant,+nullDereference</arg>
            <arg>-nowarn:[${project.build.directory}/generated-sources]</arg>
          </compilerArgs>
          <showWarnings>true</showWarnings>
          <showDeprecation>true</showDeprecation>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.codehaus.plexus</groupId>
            <artifactId>plexus-compiler-eclipse</artifactId>
            <version>2.16.2</version>
          </dependency>
          <dependency>
            <groupId>org.eclipse.jdt</groupId>
            <artifactId>ecj</artifactId>
            <version>3.36.0</version>
          </dependency>
        </dependencies>
      </plugin>
    </plugins>
    <extensions>
      <extension>
        <groupId>org.openhab.tools.sat</groupId>
        <artifactId>sat-extension</artifactId>
        <version>${sat.version}</version>
      </extension>
    </extensions>
  </build>
</project>
